name: Deploy to prod

on:
  push:
    branches:
      - production

jobs:
  redeploy:
    name: Deploying the app to prod
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: 54.172.80.133
          username: anuj
          key: ${{ secrets.SSH_SECRET_KEY_PROD }}
          port: 22
          script: |
            cd bms
            git pull origin production
            pnpm install
            pnpm build
            pm2 restart http-server
            pm2 restart web-server
            pm2 restart socket-server
